In [1]:
import requests
import pandas as pd
import numpy as np

In [4]:
latitude = 13.133521
longitude = 77.567135
radius = 5000

In [5]:
API_KEY = "T3BSR4PNMDJCA4PDZ3KHF3LGRP03LW4OIUZLHRIZP003GQZU"

In [6]:
url = "https://places-api.foursquare.com/places/search"

headers = {
    "Authorization": f"Bearer {API_KEY}",
    "X-Places-Api-Version": "2025-06-17",
    "Accept": "application/json"
}

params = {
    "ll": f"{latitude},{longitude}",
    "query": "restaurant",
    "radius": 2000,
    "limit": 20
}

response = requests.get(
    url,
    headers=headers,
    params=params
)

print(response.status_code)

200

In [7]:
data = response.json()

data

{'results': [{'fsq_place_id': '64e0c605ffdf322ba552d3a6',
   'latitude': 13.133341,
   'longitude': 77.57008,
   'categories': [{'fsq_category_id': '4bf58dd8d48988d16e941735',
     'name': 'Fast Food Restaurant',
     'short_name': 'Fast Food',
     'plural_name': 'Fast Food Restaurants',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/fastfood_',
      'suffix': '.png'}}],
   'chains': [{'fsq_chain_id': '556f7a12bd6a75a9903bddb2',
     'name': "McDonald's"}],
   'date_created': '2023-08-19',
   'date_refreshed': '2024-03-19',
   'distance': 319,
   'extended_location': {},
   'link': '/places/64e0c605ffdf322ba552d3a6',
   'location': {'address': 'Opp to BMSIT',
    'locality': 'Bangalore',
    'region': 'Karnātaka',
    'postcode': '560064',
    'country': 'IN',
    'formatted_address': 'Opp to BMSIT, Bangalore 560064, Karnātaka'},
   'name': "McDonald's",
   'placemaker_url': 'https://foursquare.com/placemakers/review-place/64e0c605ffdf322ba552d3a6',
   'related_places': {},
   'social_media': {'facebook_id': '109393465767252',
    'instagram': 'mcdonalds_india',
    'twitter': 'mcdonaldsindia'},
   'website': 'https://www.mcdonaldsindia.com'},
  {'fsq_place_id': '4d7c79df136bf04d505a608d',
   'latitude': 13.136401671816362,
   'longitude': 77.57149906667286,
   'categories': [{'fsq_category_id': '4bf58dd8d48988d10f941735',
     'name': 'Indian Restaurant',
     'short_name': 'Indian',
     'plural_name': 'Indian Restaurants',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/indian_',
      'suffix': '.png'}}],
   'date_created': '2011-03-13',
   'date_refreshed': '2017-01-20',
   'distance': 570,
   'extended_location': {},
   'link': '/places/4d7c79df136bf04d505a608d',
   'location': {'region': 'Gujarat',
    'postcode': '',
    'country': 'IN',
    'formatted_address': 'Gujarat'},
   'name': 'The Green House',
   'placemaker_url': 'https://foursquare.com/placemakers/review-place/4d7c79df136bf04d505a608d',
   'related_places': {},
   'social_media': {'twitter': ''},
   'tel': '079 2550 6899'},
  {'fsq_place_id': '62dc23c65c7612699f4e8b0b',
   'latitude': 13.126917,
   'longitude': 77.566385,
   'categories': [{'fsq_category_id': '4d4b7105d754a06374d81259',
     'name': 'Restaurant',
     'short_name': 'Restaurant',
     'plural_name': 'Restaurants',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/default_',
      'suffix': '.png'}}],
   'date_created': '2022-07-23',
   'date_refreshed': '2023-11-09',
   'distance': 738,
   'extended_location': {},
   'link': '/places/62dc23c65c7612699f4e8b0b',
   'location': {'address': 'Jinvara',
    'locality': 'Bangalore',
    'region': 'Karnātaka',
    'postcode': '560064',
    'country': 'IN',
    'formatted_address': 'Jinvara (Yelahanka), Bangalore 560064, Karnātaka'},
   'name': 'Marmalade Kitchen & Bar',
   'placemaker_url': 'https://foursquare.com/placemakers/review-place/62dc23c65c7612699f4e8b0b',
   'related_places': {},
   'social_media': {'twitter': ''}},
  {'fsq_place_id': '651a78c5a0a1fa160fb77d74',
   'latitude': 13.126454,
   'longitude': 77.56621,
   'categories': [{'fsq_category_id': '4bf58dd8d48988d10c941735',
     'name': 'French Restaurant',
     'short_name': 'French',
     'plural_name': 'French Restaurants',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/french_',
      'suffix': '.png'}}],
   'date_created': '2023-10-02',
   'date_refreshed': '2026-07-05',
   'distance': 791,
   'extended_location': {},
   'link': '/places/651a78c5a0a1fa160fb77d74',
   'location': {'address': 'Shop 15, Jinvara, Avalahalli',
    'locality': 'Bangalore',
    'region': 'Karnātaka',
    'postcode': '560064',
    'country': 'IN',
    'formatted_address': 'Shop 15, Jinvara, Avalahalli (Yelahanka), Bangalore 560064, Karnātaka'},
   'name': 'The French Treaty',
   'placemaker_url': 'https://foursquare.com/placemakers/review-place/651a78c5a0a1fa160fb77d74',
   'related_places': {},
   'social_media': {'twitter': ''}},
  {'fsq_place_id': '50fbb9a1e4b0aa46b66ee7f8',
   'latitude': 13.145139688294375,
   'longitude': 77.57004945384895,
   'categories': [{'fsq_category_id': '4bf58dd8d48988d10f941735',
     'name': 'Indian Restaurant',
     'short_name': 'Indian',
     'plural_name': 'Indian Restaurants',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/indian_',
      'suffix': '.png'}}],
   'date_created': '2013-01-20',
   'date_refreshed': '2024-08-23',
   'distance': 1329,
   'extended_location': {},
   'link': '/places/50fbb9a1e4b0aa46b66ee7f8',
   'location': {'address': 'Singhanayaka Hallu',
    'locality': 'Bangalore',
    'region': 'Karnātaka',
    'postcode': '',
    'country': 'IN',
    'formatted_address': 'Singhanayaka Hallu (Doddabalapura Main Road), Bangalore, Karnātaka'},
   'name': 'Bhagini Pavilion',
   'placemaker_url': 'https://foursquare.com/placemakers/review-place/50fbb9a1e4b0aa46b66ee7f8',
   'related_places': {},
   'social_media': {'twitter': ''},
   'tel': '080 3256 3331',
   'website': 'http://bhaginipavilion.com'},
  {'fsq_place_id': '5228a86e11d24e01fc5cb199',
   'latitude': 13.11592269018241,
   'longitude': 77.56440754082148,
   'categories': [{'fsq_category_id': '4bf58dd8d48988d10f941735',
     'name': 'Indian Restaurant',
     'short_name': 'Indian',
     'plural_name': 'Indian Restaurants',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/indian_',
      'suffix': '.png'}}],
   'date_created': '2013-09-05',
   'date_refreshed': '2013-09-22',
   'distance': 1977,
   'extended_location': {},
   'link': '/places/5228a86e11d24e01fc5cb199',
   'location': {'postcode': '', 'country': 'IN', 'formatted_address': ''},
   'name': 'New Annapurna fast food',
   'placemaker_url': 'https://foursquare.com/placemakers/review-place/5228a86e11d24e01fc5cb199',
   'related_places': {},
   'social_media': {'twitter': ''}},
  {'fsq_place_id': '5cdee79cf1fdaf0030241fde',
   'latitude': 13.11629,
   'longitude': 77.562546,
   'categories': [{'fsq_category_id': '54135bf5e4b08f3d2429dfe5',
     'name': 'Andhra Restaurant',
     'short_name': 'Andhra',
     'plural_name': 'Andhra Restaurants',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/default_',
      'suffix': '.png'}}],
   'date_created': '2019-05-17',
   'date_refreshed': '2019-08-24',
   'distance': 1978,
   'extended_location': {},
   'link': '/places/5cdee79cf1fdaf0030241fde',
   'location': {'address': 'Near Nagarjuna College, Ananthapura',
    'locality': 'Bangalore',
    'region': 'Karnātaka',
    'postcode': '560064',
    'country': 'IN',
    'formatted_address': 'Near Nagarjuna College, Ananthapura (Yelahanka), Bangalore 560064, Karnātaka'},
   'name': 'Delight Andhra Cafeteria',
   'placemaker_url': 'https://foursquare.com/placemakers/review-place/5cdee79cf1fdaf0030241fde',
   'related_places': {},
   'social_media': {'twitter': ''}}],
 'context': {'geo_bounds': {'circle': {'center': {'latitude': 13.133521,
     'longitude': 77.567135},
    'radius': 2000}}}}

In [8]:
data.keys()

dict_keys(['results', 'context'])

In [9]:
params = {
    "ll": f"{latitude},{longitude}",
    "query": "apartment",
    "radius": 5000,
    "limit": 50
}

In [10]:
len(data['results'])

7

In [11]:
data['results'][0]

{'fsq_place_id': '64e0c605ffdf322ba552d3a6',
 'latitude': 13.133341,
 'longitude': 77.57008,
 'categories': [{'fsq_category_id': '4bf58dd8d48988d16e941735',
   'name': 'Fast Food Restaurant',
   'short_name': 'Fast Food',
   'plural_name': 'Fast Food Restaurants',
   'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/fastfood_',
    'suffix': '.png'}}],
 'chains': [{'fsq_chain_id': '556f7a12bd6a75a9903bddb2',
   'name': "McDonald's"}],
 'date_created': '2023-08-19',
 'date_refreshed': '2024-03-19',
 'distance': 319,
 'extended_location': {},
 'link': '/places/64e0c605ffdf322ba552d3a6',
 'location': {'address': 'Opp to BMSIT',
  'locality': 'Bangalore',
  'region': 'Karnātaka',
  'postcode': '560064',
  'country': 'IN',
  'formatted_address': 'Opp to BMSIT, Bangalore 560064, Karnātaka'},
 'name': "McDonald's",
 'placemaker_url': 'https://foursquare.com/placemakers/review-place/64e0c605ffdf322ba552d3a6',
 'related_places': {},
 'social_media': {'facebook_id': '109393465767252',
  'instagram': 'mcdonalds_india',
  'twitter': 'mcdonaldsindia'},
 'website': 'https://www.mcdonaldsindia.com'}

In [12]:
data['results'][0].keys()

dict_keys(['fsq_place_id', 'latitude', 'longitude', 'categories', 'chains', 'date_created', 'date_refreshed', 'distance', 'extended_location', 'link', 'location', 'name', 'placemaker_url', 'related_places', 'social_media', 'website'])

In [13]:
places_df = pd.json_normalize(data['results'])

places_df.head()

,fsq_place_id,latitude,longitude,categories,chains,date_created,date_refreshed,distance,link,name,...,location.address,location.locality,location.region,location.postcode,location.country,location.formatted_address,social_media.facebook_id,social_media.instagram,social_media.twitter,tel
0,64e0c605ffdf322ba552d3a6,13.133341,77.570080,[{'fsq_category_id': '4bf58dd8d48988d16e941735...,"[{'fsq_chain_id': '556f7a12bd6a75a9903bddb2', ...",2023-08-19,2024-03-19,319,/places/64e0c605ffdf322ba552d3a6,McDonald's,...,Opp to BMSIT,Bangalore,Karnātaka,560064,IN,"Opp to BMSIT, Bangalore 560064, Karnātaka",109393465767252,mcdonalds_india,mcdonaldsindia,NaN
1,4d7c79df136bf04d505a608d,13.136402,77.571499,[{'fsq_category_id': '4bf58dd8d48988d10f941735...,NaN,2011-03-13,2017-01-20,570,/places/4d7c79df136bf04d505a608d,The Green House,...,NaN,NaN,Gujarat,,IN,Gujarat,NaN,NaN,,079 2550 6899
2,62dc23c65c7612699f4e8b0b,13.126917,77.566385,[{'fsq_category_id': '4d4b7105d754a06374d81259...,NaN,2022-07-23,2023-11-09,738,/places/62dc23c65c7612699f4e8b0b,Marmalade Kitchen & Bar,...,Jinvara,Bangalore,Karnātaka,560064,IN,"Jinvara (Yelahanka), Bangalore 560064, Karnātaka",NaN,NaN,,NaN
3,651a78c5a0a1fa160fb77d74,13.126454,77.566210,[{'fsq_category_id': '4bf58dd8d48988d10c941735...,NaN,2023-10-02,2026-07-05,791,/places/651a78c5a0a1fa160fb77d74,The French Treaty,...,"Shop 15, Jinvara, Avalahalli",Bangalore,Karnātaka,560064,IN,"Shop 15, Jinvara, Avalahalli (Yelahanka), Bang...",NaN,NaN,,NaN
4,50fbb9a1e4b0aa46b66ee7f8,13.145140,77.570049,[{'fsq_category_id': '4bf58dd8d48988d10f941735...,NaN,2013-01-20,2024-08-23,1329,/places/50fbb9a1e4b0aa46b66ee7f8,Bhagini Pavilion,...,Singhanayaka Hallu,Bangalore,Karnātaka,,IN,"Singhanayaka Hallu (Doddabalapura Main Road), ...",NaN,NaN,,080 3256 3331

In [14]:
places_df.columns.tolist()

['fsq_place_id',
 'latitude',
 'longitude',
 'categories',
 'chains',
 'date_created',
 'date_refreshed',
 'distance',
 'link',
 'name',
 'placemaker_url',
 'website',
 'location.address',
 'location.locality',
 'location.region',
 'location.postcode',
 'location.country',
 'location.formatted_address',
 'social_media.facebook_id',
 'social_media.instagram',
 'social_media.twitter',
 'tel']

In [15]:
locations = places_df[[
    'name',
    'latitude',
    'longitude',
    'location.formatted_address',
    'distance'
]].copy()

In [16]:
locations.head()

,name,latitude,longitude,location.formatted_address,distance
0,McDonald's,13.133341,77.570080,"Opp to BMSIT, Bangalore 560064, Karnātaka",319
1,The Green House,13.136402,77.571499,Gujarat,570
2,Marmalade Kitchen & Bar,13.126917,77.566385,"Jinvara (Yelahanka), Bangalore 560064, Karnātaka",738
3,The French Treaty,13.126454,77.566210,"Shop 15, Jinvara, Avalahalli (Yelahanka), Bang...",791
4,Bhagini Pavilion,13.145140,77.570049,"Singhanayaka Hallu (Doddabalapura Main Road), ...",1329

In [17]:
params = {
    "ll": f"{latitude},{longitude}",
    "query": "apartment",
    "radius": 5000,
    "limit": 50
}

response = requests.get(
    url,
    headers=headers,
    params=params
)

data = response.json()

In [18]:
len(data['results'])

19

In [19]:
places_df = pd.json_normalize(data['results'])
places_df.head()

,fsq_place_id,latitude,longitude,categories,date_created,date_refreshed,distance,link,name,placemaker_url,...,location.address,location.locality,location.region,tel,related_places.children,website,email,related_places.parent.fsq_place_id,related_places.parent.categories,related_places.parent.name
0,56ac9283498e7cbb284553da,13.134563,77.572646,[{'fsq_category_id': '4d954b06a243a5684965b473...,2016-01-30,2019-01-19,607,/places/56ac9283498e7cbb284553da,Shriram Suhaana Apartments,https://foursquare.com/placemakers/review-plac...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,51319d59e4b04a7c6799abe4,13.114882,77.563090,[{'fsq_category_id': '4d954b06a243a5684965b473...,2013-03-02,2026-07-12,2117,/places/51319d59e4b04a7c6799abe4,GK Lakeview Apartment,https://foursquare.com/placemakers/review-plac...,...,Ananthapura Road,Bangalore,Karnātaka,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4f58dcb6e4b0ff115978a5ba,13.130488,77.572826,[{'fsq_category_id': '4d954b06a243a5684965b473...,2012-03-08,2015-04-01,702,/places/4f58dcb6e4b0ff115978a5ba,shobha azalia,https://foursquare.com/placemakers/review-plac...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5cf2990fb3d8e2002c5c63ae,13.138822,77.571338,[{'fsq_category_id': '4d954b06a243a5684965b473...,2019-06-01,2025-09-14,744,/places/5cf2990fb3d8e2002c5c63ae,Prestige Royal Garden,https://foursquare.com/placemakers/review-plac...,...,Avalahalli,Bangalore,Karnātaka,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,57d3aaa5498e9102adec5e6b,13.128440,77.561760,[{'fsq_category_id': '4d954b06a243a5684965b473...,2016-09-10,2026-06-24,810,/places/57d3aaa5498e9102adec5e6b,Prestige Garden Bay,https://foursquare.com/placemakers/review-plac...,...,"Behind Crpf Underground, Yelahanka Satellite Town",Bangalore,Karnātaka,080 2559 1080,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
amenities = [
    "restaurant",
    "grocery store",
    "gym"
]

In [21]:
test_lat = locations.iloc[0]['latitude']
test_lon = locations.iloc[0]['longitude']

print(test_lat, test_lon)

13.133341 77.57008

In [22]:
params = {
    "ll": f"{test_lat},{test_lon}",
    "query": "restaurant",
    "radius": 1500,
    "limit": 50
}

response = requests.get(
    url,
    headers=headers,
    params=params
)

restaurant_data = response.json()

In [23]:
len(restaurant_data['results'])

5

In [24]:
params = {
    "ll": f"{test_lat},{test_lon}",
    "query": "grocery store",
    "radius": 1500,
    "limit": 50
}

response = requests.get(url, headers=headers, params=params)
grocery_data = response.json()

print(len(grocery_data['results']))

3

In [25]:
params = {
    "ll": f"{test_lat},{test_lon}",
    "query": "gym",
    "radius": 1500,
    "limit": 50
}

response = requests.get(url, headers=headers, params=params)
gym_data = response.json()

print(len(gym_data['results']))

2

In [26]:
def count_amenity(lat, lon, amenity):

    params = {
        "ll": f"{lat},{lon}",
        "query": amenity,
        "radius": 1500,
        "limit": 50
    }

    response = requests.get(
        url,
        headers=headers,
        params=params
    )

    data = response.json()

    return len(data.get('results', []))

In [27]:
count_amenity(test_lat, test_lon, "restaurant")

5

In [28]:
locations['restaurants'] = locations.apply(
    lambda row: count_amenity(
        row['latitude'],
        row['longitude'],
        'restaurant'
    ),
    axis=1
)

In [29]:
locations['grocery_stores'] = locations.apply(
    lambda row: count_amenity(
        row['latitude'],
        row['longitude'],
        'grocery store'
    ),
    axis=1
)

In [30]:
locations['gyms'] = locations.apply(
    lambda row: count_amenity(
        row['latitude'],
        row['longitude'],
        'gym'
    ),
    axis=1
)

In [31]:
locations.head()

,name,latitude,longitude,location.formatted_address,distance,restaurants,grocery_stores,gyms
0,McDonald's,13.133341,77.570080,"Opp to BMSIT, Bangalore 560064, Karnātaka",319,5,3,2
1,The Green House,13.136402,77.571499,Gujarat,570,5,3,2
2,Marmalade Kitchen & Bar,13.126917,77.566385,"Jinvara (Yelahanka), Bangalore 560064, Karnātaka",738,13,2,2
3,The French Treaty,13.126454,77.566210,"Shop 15, Jinvara, Avalahalli (Yelahanka), Bang...",791,13,2,2
4,Bhagini Pavilion,13.145140,77.570049,"Singhanayaka Hallu (Doddabalapura Main Road), ...",1329,10,2,2

In [32]:
locations[['restaurants', 'grocery_stores', 'gyms']].describe()

       restaurants  grocery_stores      gyms
count     7.000000        7.000000  7.000000
mean     10.428571        1.714286  1.571429
std       4.157609        1.253566  0.786796
min       5.000000        0.000000  0.000000
25%       7.500000        1.000000  1.500000
50%      11.000000        2.000000  2.000000
75%      13.000000        2.500000  2.000000
max      16.000000        3.000000  2.000000

In [33]:
location_features = locations[[
    'restaurants',
    'grocery_stores',
    'gyms'
]].copy()

In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_location = scaler.fit_transform(location_features)

In [35]:
optimal_k = 2

In [36]:
from sklearn.cluster import KMeans

kmeans_location = KMeans(
    n_clusters=optimal_k,
    random_state=42,
    n_init=10
)

locations['Cluster'] = kmeans_location.fit_predict(X_location)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

In [37]:
locations.head()

,name,latitude,longitude,location.formatted_address,distance,restaurants,grocery_stores,gyms,Cluster
0,McDonald's,13.133341,77.570080,"Opp to BMSIT, Bangalore 560064, Karnātaka",319,5,3,2,0
1,The Green House,13.136402,77.571499,Gujarat,570,5,3,2,0
2,Marmalade Kitchen & Bar,13.126917,77.566385,"Jinvara (Yelahanka), Bangalore 560064, Karnātaka",738,13,2,2,0
3,The French Treaty,13.126454,77.566210,"Shop 15, Jinvara, Avalahalli (Yelahanka), Bang...",791,13,2,2,0
4,Bhagini Pavilion,13.145140,77.570049,"Singhanayaka Hallu (Doddabalapura Main Road), ...",1329,10,2,2,0

In [38]:
locations.groupby('Cluster')[
    ['restaurants', 'grocery_stores', 'gyms']
].mean()

         restaurants  grocery_stores  gyms
Cluster
0                9.2             2.4   2.0
1               13.5             0.0   0.5

In [39]:
!pip install folium

Collecting folium
  Downloading folium-0.20.0-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting branca>=0.6.0 (from folium)
  Downloading branca-0.8.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: jinja2>=2.9 in c:\programdata\anaconda3\lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from folium) (2.1.3)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in c:\programdata\anaconda3\lib\site-packages (from folium) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->folium) (2025.6.15)
Downloading folium-0.20.0-py2.py3-none-any.whl (113 kB)
Downloading branca-0.8.2-py3-none-any.whl (26 kB)
Installing collected packages: branca, folium

   ---------------------------------------- 2/2 [folium]

Successfully installed branca-0.8.2 folium-0.20.0

In [40]:
import folium

In [41]:
bangalore_map = folium.Map(
    location=[13.133521, 77.567135],
    zoom_start=11
)

bangalore_map

In [42]:
colors = {
    0: 'red',
    1: 'blue',
    2: 'green'
}

for _, row in locations.iterrows():

    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=7,
        popup=f"""
        {row['name']}<br>
        Cluster: {row['Cluster']}<br>
        Restaurants: {row['restaurants']}<br>
        Groceries: {row['grocery_stores']}<br>
        Gyms: {row['gyms']}
        """,
        color=colors[row['Cluster']],
        fill=True,
        fill_color=colors[row['Cluster']],
        fill_opacity=0.7
    ).add_to(bangalore_map)

In [43]:
bangalore_map